/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSuggestRouteImport } from './routes/api/public/suggest'
import { Route as ApiPublicBareSplatRouteImport } from './routes/api/public/bare.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSuggestRoute = ApiPublicSuggestRouteImport.update({
  id: '/api/public/suggest',
  path: '/api/public/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBareSplatRoute = ApiPublicBareSplatRouteImport.update({
  id: '/api/public/bare/$',
  path: '/api/public/bare/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/suggest': typeof ApiPublicSuggestRoute
  '/api/public/bare/$': typeof ApiPublicBareSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/suggest': typeof ApiPublicSuggestRoute
  '/api/public/bare/$': typeof ApiPublicBareSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/suggest': typeof ApiPublicSuggestRoute
  '/api/public/bare/$': typeof ApiPublicBareSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/suggest' | '/api/public/bare/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/suggest' | '/api/public/bare/$'
  id: '__root__' | '/' | '/api/public/suggest' | '/api/public/bare/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSuggestRoute: typeof ApiPublicSuggestRoute
  ApiPublicBareSplatRoute: typeof ApiPublicBareSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/suggest': {
      id: '/api/public/suggest'
      path: '/api/public/suggest'
      fullPath: '/api/public/suggest'
      preLoaderRoute: typeof ApiPublicSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bare/$': {
      id: '/api/public/bare/$'
      path: '/api/public/bare/$'
      fullPath: '/api/public/bare/$'
      preLoaderRoute: typeof ApiPublicBareSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSuggestRoute: ApiPublicSuggestRoute,
  ApiPublicBareSplatRoute: ApiPublicBareSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
